### ISSUE TITLE
New Issues

### ISSUE THREAD

**Issue by EmmaSweeney** [javamanatee/thomas-hardy_a-pair-of-blue-eyes#2]
dramatis-personae.xhtml:

- [x] Rename the scene's `<section>` id as `id="dramatis-personae-scene"`.

chapter-2.xhtml:

- [x] Remove the trailing periods in the numbered letter headers.

chapter-20.xhtml:

- [x] Tag `<p>Johnson, Liverpool, to Miss Swancourt, Endelstow, near Castle Boterel.</p>` with `epub:type="se:letter.dateline"` and put it in a `<header>` element.

local.css:

- [x] Adjust the header CSS to be:
```
header,
#chapter-2 blockquote header p:first-child{
	font-variant: small-caps;
	margin: 1em;
	text-align: center;
}
```

- [x] Adjust the postscript CSS to be:
```
[epub|type~="z3998:postscript"]{
	margin: 1em 0 1em 0;
	text-align: initial;
	text-indent: 0;
}
```

- [x] Adjust the letter CSS to be:
```
/* letters */
[epub|type~="z3998:letter"] header{
	font-variant: normal;
	margin: 0;
	text-align: right;
}
...
```

- [x] Add CSS for epigraphs in section headers ([SEMOS 7.4.5](https://standardebooks.org/manual/1.7.0/single-page#7.4.5)).

- [x] Add the following to the dramatis personae CSS:
```
[epub|type~="z3998:dramatis-personae"] ul + section{
	margin-top: 2em;
}
```

- [x] Remove:
```
#chapter-20 [epub|type~="z3998:letter"] p{
	margin-top: 1em;
	text-indent: 0;
}
...
/* preface */
#preface [epub|type~="z3998:signature"]{
	margin-top: 1em;
	text-align: right;
}
/* end preface */

/* special letter header */
#chapter-2 header p:first-child{
	margin-bottom: 1em;
	text-align: center;
}
/* end special letter header */

#dramatis-personae header{
	margin-top: 2em;
}

#dramatis-personae header + p{
	margin-top: 1em;
}
```

**Comment by javamanatee** [comment]
Done.
